name: Tests Only

on:
  push:
    branches: [ "testing-auth-framework" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          
      - name: Install dependencies
        run: npm install
          
      - name: Run tests only
        run: npm run test:run
        
      - name: Generate coverage report
        run: npm run test:coverage